version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/MasatoTokuse/circleci
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...